name: Build Android APKs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Install Gradle
        run: sudo apt-get install gradle -y

      - name: Build Admin App
        run: |
          cd AdminApp
          gradle assembleDebug

      - name: Build User App
        run: |
          cd UserApp
          gradle assembleDebug

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: Built-APKs
          path: |
            AdminApp/app/build/outputs/apk/debug/app-debug.apk
            UserApp/app/build/outputs/apk/debug/app-debug.apk
